# Generated by Django 4.1.7 on 2023-03-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_alter_hotel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
