# Generated by Django 4.1.7 on 2023-03-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_location_alter_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.location'),
        ),
    ]
