# Generated by Django 4.1.7 on 2023-03-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0003_booking_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
